[package]
name = "ethornell-app"
version = "0.1.0"
edition.workspace = true

[dependencies]
ethornell-core = { path = "../ethornell-core" }
ethornell-archive = { path = "../ethornell-archive" }
ethornell-image = { path = "../ethornell-image" }
ethornell-render = { path = "../ethornell-render" }
ethornell-audio = { path = "../ethornell-audio" }
ethornell-script = { path = "../ethornell-script" }
ethornell-vm = { path = "../ethornell-vm" }
na_mpeg2_decoder = { path = "../na_mpeg2_decoder", default-features = false, features = ["video-only"] }
ruffle_core = { git = "https://github.com/ruffle-rs/ruffle.git", tag = "v0.4.1", features = ["default_font", "lzma", "mp3", "aac", "nellymoser"] }
ruffle_render_wgpu = { git = "https://github.com/ruffle-rs/ruffle.git", tag = "v0.4.1" }
ab_glyph.workspace = true
encoding_rs.workspace = true
pollster.workspace = true
tracing.workspace = true
winit.workspace = true
